// create_trip_screen.dart
// Form dialog page that creates a Trip model and returns it to the caller via pop.

import 'dart:math';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/models.dart';
import '../data/dummy_data.dart';
import '../services/firestore_service.dart';

class CreateTripScreen extends StatefulWidget {
  const CreateTripScreen({super.key});

  @override
  State<CreateTripScreen> createState() => _CreateTripScreenState();
}

class _CreateTripScreenState extends State<CreateTripScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _startingPointController = TextEditingController();
  final _budgetController = TextEditingController(text: '2500');
  
  DateTime? _startDate;
  DateTime? _endDate;

  final DateFormat _dateFormat = DateFormat('yyyy-MM-dd');

  // Hardcoded cover images list to pick at random for the new trip
  final List<String> _mockCovers = [
    'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop',
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _startingPointController.dispose();
    _budgetController.dispose();
    super.dispose();
  }

  Future<void> _selectStartDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _startDate ?? DateTime.now().add(const Duration(days: 1)),
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now().add(const Duration(days: 3650)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: Theme.of(context).colorScheme.copyWith(
              primary: const Color(0xFF6366F1),
            ),
          ),
          child: child!,
        );
      },
    );

    if (picked != null && picked != _startDate) {
      setState(() {
        _startDate = picked;
        // Reset end date if it is before start date
        if (_endDate != null && _endDate!.isBefore(_startDate!)) {
          _endDate = null;
        }
      });
    }
  }

  Future<void> _selectEndDate() async {
    if (_startDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a start date first')),
      );
      return;
    }

    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _endDate ?? _startDate!.add(const Duration(days: 1)),
      firstDate: _startDate!,
      lastDate: _startDate!.add(const Duration(days: 365)),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: Theme.of(context).colorScheme.copyWith(
              primary: const Color(0xFF6366F1),
            ),
          ),
          child: child!,
        );
      },
    );

    if (picked != null && picked != _endDate) {
      setState(() {
        _endDate = picked;
      });
    }
  }

  bool _isLoading = false;

  void _saveTrip() async {
    if (_formKey.currentState!.validate()) {
      if (_startDate == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select a start date')),
        );
        return;
      }
      if (_endDate == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select an end date')),
        );
        return;
      }

      final parsedBudget = double.tryParse(_budgetController.text.trim()) ?? 0.0;
      if (parsedBudget <= 0) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please enter a valid positive budget amount')),
        );
        return;
      }

      setState(() {
        _isLoading = true;
      });

      try {
        final randomCover = _mockCovers[Random().nextInt(_mockCovers.length)];
        final newTrip = Trip(
          id: '', // Generated by Firestore
          name: _nameController.text.trim(),
          startingPoint: _startingPointController.text.trim(),
          coverImageUrl: randomCover,
          startDate: _startDate!,
          endDate: _endDate!,
          budget: parsedBudget,
          activities: [],
          expenses: [],
          memories: [],
          packingList: [
            PackingItem(id: 'pack_c1', name: 'Toiletries Kit', isPacked: false),
            PackingItem(id: 'pack_c2', name: 'Charger & Power Bank', isPacked: false),
            PackingItem(id: 'pack_c3', name: 'Comfortable Clothing', isPacked: false),
          ],
        );

        final user = FirebaseAuth.instance.currentUser;
        if (user != null) {
          await FirestoreService.instance.addTrip(newTrip, user.uid);
          if (mounted) {
            Navigator.pop(context, true);
          }
        } else {
          throw Exception('User not authenticated');
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Failed to save trip: $e'),
              backgroundColor: Colors.redAccent,
            ),
          );
        }
      } finally {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    final isTablet = mediaQuery.size.width > 600;

    final String currencyCode = DummyData.userProfile['homeCurrency'] ?? 'USD';
    String currencySymbol = '\$';
    if (currencyCode == 'PKR') {
      currencySymbol = 'Rs ';
    } else if (currencyCode == 'EUR') {
      currencySymbol = '€';
    } else if (currencyCode == 'JPY') {
      currencySymbol = '¥';
    } else if (currencyCode == 'CHF') {
      currencySymbol = 'Fr';
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Plan New Trip'),
        centerTitle: true,
      ),
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: EdgeInsets.symmetric(
              horizontal: isTablet ? mediaQuery.size.width * 0.15 : 20.0,
              vertical: 16.0,
            ),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Visual header representation
                  Icon(
                    Icons.map_rounded,
                    size: 64,
                    color: const Color(0xFF6366F1).withOpacity(0.8),
                  ),
                  const SizedBox(height: 12),
                  const Text(
                    'Where to next?',
                    textAlign: TextAlign.center,
                    style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 24),

                  // Starting Point (Origin) TextField
                  TextFormField(
                    controller: _startingPointController,
                    style: const TextStyle(color: Colors.white),
                    decoration: InputDecoration(
                      labelText: 'Starting Point (Origin)',
                      hintText: 'e.g. Islamabad, Pakistan',
                      labelStyle: const TextStyle(color: Colors.white70),
                      prefixIcon: const Icon(Icons.my_location_rounded, color: Color(0xFF818CF8)),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: Colors.white.withOpacity(0.3)),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Color(0xFF818CF8)),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your starting location';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),

                  // Destination Name TextField
                  TextFormField(
                    controller: _nameController,
                    autofocus: true,
                    style: const TextStyle(color: Colors.white),
                    decoration: InputDecoration(
                      labelText: 'Destination Name',
                      hintText: 'e.g. Hawaii, Murree, Paris',
                      labelStyle: const TextStyle(color: Colors.white70),
                      prefixIcon: const Icon(Icons.pin_drop_rounded, color: Color(0xFF818CF8)),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: Colors.white.withOpacity(0.3)),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Color(0xFF818CF8)),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter a destination';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 20),

                  // Start and End Date selection in side-by-side or stacked style
                  isTablet
                      ? Row(
                          children: [
                            Expanded(child: _buildStartDateTile()),
                            const SizedBox(width: 16),
                            Expanded(child: _buildEndDateTile()),
                          ],
                        )
                      : Column(
                          children: [
                            _buildStartDateTile(),
                            const SizedBox(height: 16),
                            _buildEndDateTile(),
                          ],
                        ),
                  const SizedBox(height: 20),

                  // Manual Budget TextField (replaces slider)
                  TextFormField(
                    controller: _budgetController,
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    style: const TextStyle(color: Colors.white),
                    decoration: InputDecoration(
                      labelText: 'Trip Budget Limit ($currencySymbol)',
                      hintText: 'e.g. 2500',
                      labelStyle: const TextStyle(color: Colors.white70),
                      prefixIcon: const Icon(Icons.account_balance_wallet_rounded, color: Color(0xFF818CF8)),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: Colors.white.withOpacity(0.3)),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: const BorderSide(color: Color(0xFF818CF8)),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter a budget amount';
                      }
                      final parsed = double.tryParse(value.trim());
                      if (parsed == null || parsed <= 0) {
                        return 'Please enter a valid positive number';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 36),

                  // Action Buttons
                  ElevatedButton(
                    onPressed: _isLoading ? null : _saveTrip,
                    child: _isLoading
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              color: Colors.white,
                            ),
                          )
                        : const Text(
                            'Save Adventure',
                            style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                          ),
                  ),
                  const SizedBox(height: 12),
                  OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      minimumSize: const Size.fromHeight(50),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      side: const BorderSide(color: Colors.white24),
                    ),
                    child: const Text('Cancel', style: TextStyle(color: Colors.white60)),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildStartDateTile() {
    return InkWell(
      onTap: _selectStartDate,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: Colors.white30),
        ),
        child: Row(
          children: [
            const Icon(Icons.date_range_rounded, color: Color(0xFF818CF8)),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Start Date', style: TextStyle(fontSize: 11, color: Colors.white54)),
                const SizedBox(height: 2),
                Text(
                  _startDate == null ? 'Select Date' : _dateFormat.format(_startDate!),
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: _startDate == null ? Colors.white38 : Colors.white,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEndDateTile() {
    return InkWell(
      onTap: _selectEndDate,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: Colors.white30),
        ),
        child: Row(
          children: [
            const Icon(Icons.date_range_rounded, color: Color(0xFF818CF8)),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('End Date', style: TextStyle(fontSize: 11, color: Colors.white54)),
                const SizedBox(height: 2),
                Text(
                  _endDate == null ? 'Select Date' : _dateFormat.format(_endDate!),
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: _endDate == null ? Colors.white38 : Colors.white,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
